title: <p align="center"> HIMMA FAICHA HUBBIYA </p>

logo: "/images/image.jpg?raw=true"

description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1pTqPr3MD8d9JInb7M3SmH97pBcTKEscO/view?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/himma-faicha-hubbiya">LinkedIn</a> |
  <a href="https://github.com/himmafh">GitHub</a>
  </p>
  
  <p align="justify">
  As a fresh graduate in Statistics from Universitas Diponegoro with interests in data and programming, I possess the ability to analyze and process data. 
  I have experience in developing Android applications, am skilled in communication, and have been active in organizations related to data and public relations. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
